### ISSUE TITLE
Cannot edit feeds if the URL is long

### ISSUE THREAD

**Issue by shaggyfeng** [joethei/obsidian-rss#68]
![Screenshot (295)](https://user-images.githubusercontent.com/75353922/148449921-97ced346-c3d2-4c3a-8ebc-77f1e23ce1b1.png)

**Comment by joethei** [comment]
This is not an issue with this plugin in particular but with obsidian itself.

This CSS snippet fixes this issue.
```css
.setting-item-description {
    word-break:break-word;
    white-space:pre-line;
}
```
